//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CartService {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CartService.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на declare @date datetime = getdate()
        ///declare @date10 datetime=dateadd(day, -10, @date)
        ///declare @date20 datetime=dateadd(day, -20, @date)
        ///declare @date30 datetime=dateadd(day, -30, @date)
        ///                                                                                                                                                                                                                                                                                                            
        ///
        ///select count(1) as  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string CartDailyReport {
            get {
                return ResourceManager.GetString("CartDailyReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на delete from ShoppingCart where guid=@uid.
        /// </summary>
        internal static string CartService_DeleteCart {
            get {
                return ResourceManager.GetString("CartService_DeleteCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на delete scp
        ///
        ///           from [dbo].[ShoppingCartProducts] scp
        ///           join [dbo].[ShoppingCart] sc on scp.ShoppingCart_id=sc.id
        ///           where sc.guid = @uid.
        /// </summary>
        internal static string CartService_DeleteProducts {
            get {
                return ResourceManager.GetString("CartService_DeleteProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на if exists(select 1 from ShoppingCart where guid=@uid)
        ///begin
        ///	update ShoppingCart
        ///	set Edited=GETDATE()
        ///end
        ///else
        ///begin
        ///	insert ShoppingCart (guid, Edited, Created) values (@uid, getdate(), getdate())
        ///end
        ///
        ///select id from ShoppingCart where guid=@uid.
        /// </summary>
        internal static string CartService_GetOrCreateCartId {
            get {
                return ResourceManager.GetString("CartService_GetOrCreateCartId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT scp.[Id]
        ///                ,[Name]
        ///                ,[Cost]
        ///                ,[ForBonusPoints]
        ///                ,[Amount]
        ///                FROM [dbo].[Product] p
        ///                    join [dbo].[ShoppingCartProducts] scp on p.id=scp.Product_id
        ///                join [dbo].[ShoppingCart] sc on scp.ShoppingCart_id=sc.id
        ///                where sc.guid=@uid.
        /// </summary>
        internal static string CartService_GetProducts {
            get {
                return ResourceManager.GetString("CartService_GetProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 
        ///INSERT INTO [dbo].[ShoppingCartProducts] (
        ///            [ShoppingCart_id]
        ///            ,[Product_id]
        ///            ,[Amount]) 
        ///           VALUES(@ShoppingCart_id
        ///            ,@Product_id
        ///            ,@Amount).
        /// </summary>
        internal static string CartService_UpdateProducts {
            get {
                return ResourceManager.GetString("CartService_UpdateProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT [Id]
        ///                    FROM [dbo].[ShoppingCart]
        ///                    where Edited&lt;@expirationDate.
        /// </summary>
        internal static string ShoppingCart_GetExpirationCartIds {
            get {
                return ResourceManager.GetString("ShoppingCart_GetExpirationCartIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на delete from ShoppingCartProducts
        ///                           where ShoppingCart_id in ({0});
        ///                           delete from ShoppingCart
        ///                           where id in ({0});
        ///.
        /// </summary>
        internal static string ShoppingCart_RemoveOldCarts {
            get {
                return ResourceManager.GetString("ShoppingCart_RemoveOldCarts", resourceCulture);
            }
        }
    }
}
